### ISSUE TITLE
Fix npm version

### ISSUE THREAD

**Issue by MagicMicky** [DrDub/torchecker#4]
Hello !

I see that you fixed an issue with your module a year ago, but you never published the changement to npm ! The result is that the version on npm isn't up to date, and doesn't work at all (based on an old http link for the exit address list).

Please update your package.json and publish the changes to npm ! :-)

Moreover, if I can add something, I think there is a mistake since your are using the `http` module to request an `https` link. See [torchecker.js#L40](https://github.com/DrDub/torchecker/blob/master/lib/torchecker.js#L40)
Cheers,
Mickael

**Comment by DrDub** [comment]
Working on it. Thanks for catching the http/https issue.
